name: Osx

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build_Osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_TEST=ON
    - name: build
      run: cmake --build build
    - name: test
      run: ctest --output-on-failure
