name: Win

on:
  push:
  workflow_run:
    workflows:
      - scheduled
    branches:
    - master
    types:
      - requested

jobs:
  build_Win_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_TEST=ON
    - name: build
      run: cmake --build build
    - name: test
      run: ctest --output-on-failure
    